import Action from "./TeacherActionDropDown";
const rows = [
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
    {
        SurName: "Timber wolf",
        ForeName: "Yes",
        Email: "Science",
        Roles: 100,
        Classes: "S1CLS1",
        Actions: <Action />,
    },
];

export default rows;